### ISSUE TITLE
Support for other protocols

### ISSUE THREAD

**Issue by grobie** [tsenart/vegeta#110]
Hej Tomás!

I'm working on rolling out a DNS server implementation right now and want to send test queries against various endpoints. I noticed that vegeta does already most of the functionality I'd like to have: read targets from a file, maintain the request rate, collect results, etc.

What do you think about making the attacker working on an interface, so that the actual protocol used to send requests can be implemented in different ways?

Cheers,
Tobi

**Comment by tsenart** [comment]
Hello Tobi!

I have thought about this before but for SQL servers. I ended up going down a deep rabbit hole...
Vegeta is very coupled with HTTP semantics as it was never designed with other protocols in mind. Making Vegeta multi-protocol is doable, but it would require a major rewrite. I'm glad to more seriously work on it sometime soon to get a better picture of the extent of the effort required.
For now, if you need to get the job done quickly, a search for "dns load testing" on [Google](https://google.com?q=dns+load+testing) reveals some possible solutions. I'd love to hear your field report on using any of those tools.

Cheers,
Tomás

**Comment by ifraixedes** [comment]
In my opinion, if it's very coupled with HTTP semantics, I wouldn't transform it to a generic load tester, because I prefer to have tools which are specific but are very good for that specific purpose.

I would suggest that if vegeta have several parts which could be reused to create other specific testers, then make them available under a concrete package.

It's just an opinion without that much knowledge on the implementation.
