### ISSUE TITLE
Add support to send statistics to a statistics service.

### ISSUE THREAD

**Issue by Mistobaan** [tsenart/vegeta#115]
The scenario is this: multiple spot instances on AWS each with vegeta on it. 
- each vegeta instance start sending data to the statistics service.
- if the spot instance goes down you would not loose the data collected that far. 

for the statistics service I would use https://github.com/rcrowley/go-metrics

**Comment by tsenart** [comment]
Hey Fabrizio,

I think you can currently cover your use case with the available functionality by writing an tool which imports vegeta dumps into your stats backend of choice. Vegeta streams results as they come so the window for data loss is small but it also depends on other factors like how fast the importer would run and other buffers in between such as pipes. Since this data kind of data is traditionally not critical, I assume these non-strict reliability guarantees are a good compromise.

Here's an example I would image could solve your problem. Please let me know what you think.
```shell
$ echo "GET http://target:8080/a/b/c" | vegeta attack ... | vegeta dump | import -backend="..."
```

**Comment by Mistobaan** [comment]
Yes. I think yours is the right solution. Thank you @tsenart ! I will make a tool to import data in that way.

**Comment by Dieterbe** [comment]
@Mistobaan any chance you can share your work? i'm looking to do the same thing.
