### ISSUE TITLE
Refactor target parser

### ISSUE THREAD

**Issue by tsenart** [tsenart/vegeta#141]
The current parser code isn't very modular and could be simplified.

**Comment by ei-grad** [comment]
@tsenart hi! Thanks for a great tool.

I want to deal with target parser refactoring to be able to use it in my own load testing tool. If there are nobody working on this currently, then you could expect a pull-request from me in a month or so (so long because my own load testing project is not the main thing I work on).

Would it be ok if I move target parsing to github.com/tsenart/vegeta/target package?

Any other suggestions / requirements / whishes?

**Comment by tsenart** [comment]
Hello @ei-grad! Thanks for proposing to work on this. I suggest you approach this with small incremental steps and put all of this up for me to review regularly.

Let's start with everything in the same package as it currently is. Also please bring forward a bit more specifics of how you plan to refactor this.

**Comment by tsenart** [comment]
Closed in favor of https://github.com/tsenart/vegeta/pull/300
