### ISSUE TITLE
Am I just hitting Cloudflare?

### ISSUE THREAD

**Issue by vemv** [tsenart/vegeta#243]
First of all thank you and congratulations for this fine piece of engineering!

I'm using Vegeta to load-test my own website, protected with Cloudflare. I'm hitting it moderately, say 500 req/s from a single machine.

My app turns out to respond quite well. Or does it? How can I know I'm just not getting whatever Cloudflare responds with, to detected attackers?

With that in mind, Vegeta could accept some kind of `proof` argument: if the string is present in a given response body, then that one request was truly `OK` (green), beyond the HTTP 200 evidence.

WDYT?

Cheers - Victor

**Comment by arlukin** [comment]
If the domain you are using vegeta on point to a cloudflare ip. Which I guess it is. Your are just loadtesting a cloud flare server.

**Comment by vemv** [comment]
> Your are just loadtesting a cloud flare server.
Actually hard to know; 500 req/s (or 20, for the sake of example) might be "nothing" for Cloudflare.

Surely at _some_ point one triggers CF's treshold, but without some kind of signal from Vegeta, it's impossible to determine that.

**Comment by daluu** [comment]
Maybe this would also be a question to CF (or look up their docs)? Basically, how will CF respond if threshold is surpassed? Will it return a non 200 HTTP status code or does it do something else? I'd assume under that case it is not likely to proxy the request to your actual server, but I could be mistaken.

Also, does CF add any custom/specific HTTP headers in the response or request? Some proxies or load balancers do. If so, you can then key off that, absence of it means it didn't go through CF successfully. If on response side, you could use the custom go/golang coding capability of vegeta (not the default CLI usage) to check the headers, and throw or log some error when found missing. If on requests side, you can mine your server logs or something maybe to see when the headers added by CF are missing. If adding custom/specific HTTP header with CF is configurable per your account, then you should add that.

And on this topic, are you focused on testing CF threshold for your site/account or the amount of load your site can handle? If the latter, maybe you should set up a test design where you can hit your site directly, bypassing CF to know what your server(s) can handle for the site. You can then/also separately test as you are now how much load CF can support for you. 

I do also wonder if CF has any terms of service regarding DDOS/load testing through their service - the load you generate could be treated as a DDOS or something. I hear with Amazon, you have to give them notice that you are load testing your servers running on their infrastructure so that they properly allow you to do the test and not block/blacklist you causing your test result to be invalid.

**Comment by tsenart** [comment]
Find out your origin IPs I'd say and load test those directly, effectively bypassing your CDN.
