### ISSUE TITLE
Better customization of attacks via the library approach?

### ISSUE THREAD

**Issue by daluu** [tsenart/vegeta#267]
I haven't comprehensively looked through the vegeta codebase yet, the library option is nice. But from the sample shown in the readme, and initial glimpse of the codebase, it seems to be limited compared to say wrk and wrk2's lua scripting option, although that may or may not be limiting as well and requires one to know lua.
 
I was wondering if there's already some support not documented as examples, or any future plans for customizing the attack on a target for the library option at least.

Would be great to have a more extensible library API to customize the attack on a target, in terms of things like parsing response status code, response body, and headers for stats purposes and to use that to perhaps determine subsequent attack patterns (e.g. changing up subsequent request body and headers).

I guess this would relate to these issues on a bigger picture/scope level: #247, #263.

I'll look into this myself when I have time to poke around.

**Comment by aramalipoor** [comment]
I had a similar requirement and ended up using [wrk](https://github.com/wg/wrk) via writing a [custom script](https://gist.github.com/aramalipoor/e999bd3074da4e1beeccc3eb0f191e5e).

**Comment by daluu** [comment]
Wish I could do that with wrk/wrk2 as well, but for complex scripting (things you would do in Jmeter, gatling), Lua can be a pain to a novice, I'd prefer go with vegeta if I could. Btw, thanks for sharing your custom script, could be useful to me at some point in the future, although what I want to do with wrk/wrk2 is much more involved.

**Comment by tsenart** [comment]
Response codes and response bodies are already captured in Vegeta results. Capturing response headers would be a straightforward addition which is now tracked in #303.

As for using the library to generate targets dynamically based on live attack results, it would require `Attack` to take in a `chan *Result` instead of returning it so that you could instantiate a `Targeter` that consumes results and passes them on. I have a few ideas to improve the library API, and I'll take this use case into consideration.

**Comment by tsenart** [comment]
How would the ideas in https://github.com/tsenart/vegeta/issues/305 work for this use case?

**Comment by daluu** [comment]
I'll need to review in detail sometime, but those ideas are heading in the right direction :)
