### ISSUE TITLE
Get Body from reponse

### ISSUE THREAD

**Issue by Ankhez** [tsenart/vegeta#279]
Hi, can you help me? I can't find the one thing: how i can get body response from request?
f.e.
I have POST request and i want to extract some key's values from for use their in a new body request

**Comment by smthpickboy** [comment]
Would be really useful to return body from response in some way.

I'm using gRPC-gateway, when there's partial failure, I still have to return HTTP status 200 and include detail info in response body, because gRPC-gateway won't return response body if HTTP status is not  200.

So I have to parse response body to get meaningful statistics. I did this in my own fork, but really want this integrated into vegeta.

Thanks!

**Comment by tsenart** [comment]
I'm working on this and should have something out next weekend tops. Hold
tight! Branch: https://github.com/tsenart/vegeta/tree/response-body
