### ISSUE TITLE
Is it possible to continueously generate stress test logs when vegeta is access a service?

### ISSUE THREAD

**Issue by fengnex** [tsenart/vegeta#493]
#### Proposal

In the process of accessing any URLs, whether can vegeta output a test log record for every access request's response? Hopefully, the result record will include the following fields:
url (we may access more than one URL), status code, time consumed, bytes in, bytes out and so on

#### Background
When testing multiple urls, no way to find corresponding test results of different url.

#### Workarounds
NO

**Comment by tsenart** [comment]
Does `vegeta attack | vegeta encode` not work for you?

**Comment by fengme** [comment]
@tsenart Hi, tsenart, 

Though I admit that 'vegeta encode' is a really valuable command, we just have no way to DISTINGUISH result records of DIFFERENT URLs whenever we test more than one URL. This is what I primarily and solely concern here. 

Are there any quick solutions to address it now?

**Comment by tsenart** [comment]
The JSON results have a URL field. What makes that insufficient?

**Comment by fengme** [comment]
@tsenart Hi, gsenart:
Thanks a lot for you quick and kind help first! 
The JSON results does count! We are able to get required fields with the following extra command now:
awk -F "," '{OFS=","; print "\{"$3,$4,$5,$6,$7,$8,$11"\}"}' | jq .timestamp,.url,.latency,.code,.bytes_in,.bytes_out,.error

Without the jq block, we can get regular and plain json output, so the approach is useful.

But it seems that vegeta outputs the final results as a whole at the end of the attack instead of generating the result record one by one in the process of the stress test. As a result, simultaneously obtaining relevant trends will be impossible, including trends of accessing count, performance and so on.

So, could you be so kind as to talk about whether it is necessary and how to implement it with current versions? Thanks in advance.

**Comment by fengme** [comment]
We would be able to obtain test results in real time and continuously if we could directly query response data from vegeta when it's running. Additionally, it's also implementable if vegeta outputted relevant records into a file in real time.

**Comment by tsenart** [comment]
> Additionally, it's also implementable if vegeta outputted relevant records into a file in real time.

That's what vegeta does.

`vegeta attack | vegeta encode | tee results.json`
